/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface;

import Business.Car;
import Business.CarInformationList;
import java.awt.CardLayout;
import java.time.LocalDateTime;
import java.util.ArrayList;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author admin
 */
public class AdminViewFullDetailsJPanel extends javax.swing.JPanel {

    /**
     * Creates new form ViewFullDetailsJPanel
     */
    private Car car;
    private JPanel userProcessContainer;
    private CarInformationList carInformationList;

 
    AdminViewFullDetailsJPanel(JPanel userProcessContainer, CarInformationList carInformationList, Car carParam) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.carInformationList = carInformationList;
        this.car=carParam;
        populateAccountDetails();
    }

    private void populateAccountDetails(){
        txtAvailableCity.setText(car.getAvailble_city());
        txtBrand.setText(car.getBrand());
        if (car.isAvailable()==true){
        txtCarAvailability.setText("Yes");
        }
        else{
          txtCarAvailability.setText("No");  
        }
        if (car.isMaintenance_certificate()==true){
        txtMaintenanceCertificate.setText("Yes");
        }
        else{
          txtMaintenanceCertificate.setText("No");  
        }
        txtManufacturedYear.setText(String.valueOf(car.getManufactured_year()));
        txtMaxSeat.setText(String.valueOf(car.getMax_seats()));
        txtMinSeat.setText(String.valueOf(car.getMin_seats()));
        txtModelNo.setText(car.getModel_num());
        txtSerialNo.setText(String.valueOf(car.getSerial_num()));
        txtAvailableCity.setEnabled(false);
        txtBrand.setEnabled(false);
        txtCarAvailability.setEnabled(false);
        txtMaintenanceCertificate.setEnabled(false);
        txtManufacturedYear.setEnabled(false);
        txtMaxSeat.setEnabled(false);
        txtMinSeat.setEnabled(false);
        txtModelNo.setEnabled(false);
        txtSerialNo.setEnabled(false);
    }    
   


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */

    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel5 = new javax.swing.JLabel();
        txtMinSeat = new javax.swing.JTextField();
        txtMaxSeat = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtModelNo = new javax.swing.JTextField();
        txtAvailableCity = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        btnBack = new javax.swing.JButton();
        lblHeader = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtBrand = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtManufacturedYear = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtSerialNo = new javax.swing.JTextField();
        txtCarAvailability = new javax.swing.JTextField();
        txtMaintenanceCertificate = new javax.swing.JTextField();
        btnUpdate = new javax.swing.JButton();
        btnSave = new javax.swing.JButton();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel5.setText("Max no of Seats:");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 360, -1, 24));
        add(txtMinSeat, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 300, 210, -1));
        add(txtMaxSeat, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 360, 210, -1));

        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel6.setText("Model Number:");
        add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 120, -1, 24));

        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel7.setText("Available City:");
        add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 230, -1, 28));
        add(txtModelNo, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 120, 210, -1));
        add(txtAvailableCity, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 230, 210, -1));

        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel8.setText("Maintenance Certificate:");
        add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 290, -1, 28));

        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel9.setText("Serial Number:");
        add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 180, -1, 24));

        btnBack.setText("<Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });
        add(btnBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 69, -1, -1));

        lblHeader.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        lblHeader.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblHeader.setText("Car Details");
        add(lblHeader, new org.netbeans.lib.awtextra.AbsoluteConstraints(129, 66, 650, 32));

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel1.setText("Car Availability:");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(76, 129, -1, -1));

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel2.setText("Brand:");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(136, 189, -1, -1));

        txtBrand.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtBrandActionPerformed(evt);
            }
        });
        add(txtBrand, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 180, 210, -1));

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel3.setText("Manufactured Year:");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(54, 235, -1, -1));
        add(txtManufacturedYear, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 230, 210, -1));

        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel4.setText("Min no of Seats:");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(74, 294, -1, 24));
        add(txtSerialNo, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 180, 210, -1));
        add(txtCarAvailability, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 120, 61, -1));
        add(txtMaintenanceCertificate, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 290, 63, -1));

        btnUpdate.setText("Update");
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });
        add(btnUpdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 450, -1, -1));

        btnSave.setText("Save");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });
        add(btnSave, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 450, 80, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        userProcessContainer.remove(this);
        CardLayout cardLayout = (CardLayout)userProcessContainer.getLayout();
        cardLayout.previous(userProcessContainer);
    }//GEN-LAST:event_btnBackActionPerformed

    private void txtBrandActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtBrandActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtBrandActionPerformed

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        // TODO add your handling code here:
        
        
        txtBrand.setEnabled(true);
        txtAvailableCity.setEnabled(true);
        txtManufacturedYear.setEnabled(true);
        txtMinSeat.setEnabled(true);
        txtMaxSeat.setEnabled(true);
        txtModelNo.setEnabled(true);
        txtSerialNo.setEnabled(true);
        txtMaintenanceCertificate.setEnabled(true);
        txtCarAvailability.setEnabled(true);
        btnUpdate.setEnabled(true);
        
    }//GEN-LAST:event_btnUpdateActionPerformed

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        // TODO add your handling code here:
        
        String brand = txtBrand.getText();
        String manufacturedYear = txtManufacturedYear.getText();
        String min_seats = txtMinSeat.getText();
        String max_seats = txtMaxSeat.getText();
        String serial_num = txtSerialNo.getText();
        String model_num = txtModelNo.getText();
        String available_city = txtAvailableCity.getText();
        String ca = txtCarAvailability.getText();
        String mc = txtMaintenanceCertificate.getText();
        if(brand == null || brand.equals("")|| manufacturedYear== null || manufacturedYear.equals("") || min_seats == null || min_seats.equals("") || max_seats == null | max_seats.equals("") || serial_num == null || serial_num.equals("") || model_num== null || model_num.equals("") || available_city == null || available_city.equals("") || ca ==null || ca.equals("") || mc == null || mc.equals("")){
            JOptionPane.showMessageDialog(null, "Fields cannot be empty"); 
        return;
          }
        if (Integer.parseInt(max_seats)< Integer.parseInt(min_seats) || Integer.parseInt(max_seats)>8){
            JOptionPane.showMessageDialog(null, "Please enter a valid seat count");
            return;
        }
        if ((Integer.parseInt(manufacturedYear) < 2000 || (Integer.parseInt(manufacturedYear)>2019))){
            JOptionPane.showMessageDialog(null, "Please enter a valid year");
            return;
        }
        
        try{
        car.setAvailble_city(txtAvailableCity.getText());
        car.setBrand(txtBrand.getText());
        car.setModel_num(txtModelNo.getText());
        car.setMax_seats(Integer.parseInt(txtMaxSeat.getText()));
        car.setMin_seats(Integer.parseInt(txtMinSeat.getText()));
        car.setManufactured_year(Integer.parseInt(txtManufacturedYear.getText()));
        car.setSerial_num(Integer.parseInt(txtSerialNo.getText()));
        
        
        
        if(mc.equalsIgnoreCase("Yes"))
        {
            car.setAvailable(true);
        }
        else {
            car.setAvailable(false);
        }

        if (mc.equalsIgnoreCase("Expired"))
        {
            car.setMaintenance_certificate(true);
        }
        else
        {
            car.setMaintenance_certificate(false);
        }
        btnSave.setEnabled(false);
        btnUpdate.setEnabled(false);

        JOptionPane.showMessageDialog(null, "Account Updated Successfully");
        carInformationList.setLastUpdated(LocalDateTime.now());
        }catch (NumberFormatException e){
            
                JOptionPane.showMessageDialog(null,"Please provide valid inputs");
                return;
            }
        
        
        
        txtBrand.setEnabled(false);
        txtAvailableCity.setEnabled(false);
        txtManufacturedYear.setEnabled(false);
        txtMinSeat.setEnabled(false);
        txtMaxSeat.setEnabled(false);
        txtModelNo.setEnabled(false);
        txtSerialNo.setEnabled(false);
        txtMaintenanceCertificate.setEnabled(false);
        txtCarAvailability.setEnabled(false);
        btnUpdate.setEnabled(true);
        btnSave.setEnabled(true);
    }//GEN-LAST:event_btnSaveActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnSave;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel lblHeader;
    private javax.swing.JTextField txtAvailableCity;
    private javax.swing.JTextField txtBrand;
    private javax.swing.JTextField txtCarAvailability;
    private javax.swing.JTextField txtMaintenanceCertificate;
    private javax.swing.JTextField txtManufacturedYear;
    private javax.swing.JTextField txtMaxSeat;
    private javax.swing.JTextField txtMinSeat;
    private javax.swing.JTextField txtModelNo;
    private javax.swing.JTextField txtSerialNo;
    // End of variables declaration//GEN-END:variables
}
