/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface;

import Business.Car;
import Business.CarInformationList;
import java.awt.CardLayout;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author admin
 */
public class AdminViewJPanel extends javax.swing.JPanel {

    /**
     * Creates new form ViewJPanel
     */
    private Car car;
    private JPanel userProcessContainer;
    private CarInformationList carInformationList;
    private String person;
    public static int count;
    private List<Car> templist = new ArrayList<>();

    AdminViewJPanel(JPanel userProcessContainer, CarInformationList carInformationList, String person) {
        initComponents();
        this.person = person;
        this.userProcessContainer = userProcessContainer;
        this.carInformationList = carInformationList;
        populateTable();
    }

    public void populateTable() {
        DefaultTableModel dtm = (DefaultTableModel) searchTable.getModel();
        dtm.setRowCount(0);

        for (Car car : carInformationList.getCarList()) {

            Object row[] = new Object[6];
            row[0] = car;
            row[1] = car.getModel_num();
            row[2] = car.getMin_seats();
            row[3] = car.getMax_seats();;
            row[4] = car.getAvailble_city();
            row[5] = car.getManufactured_year();
            dtm.addRow(row);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnGroupCA = new javax.swing.ButtonGroup();
        btnGroupMC = new javax.swing.ButtonGroup();
        btnBack = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel5 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        txtSerialNumber = new javax.swing.JTextField();
        btnSerialNumber = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        txtManufacturedYear = new javax.swing.JTextField();
        SearchManufacturedYear = new javax.swing.JButton();
        jPanel9 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        seatComboBox1 = new javax.swing.JComboBox<>();
        seatComboBox2 = new javax.swing.JComboBox<>();
        btnSearchCapacity = new javax.swing.JButton();
        jPanel6 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        txtModelNumber = new javax.swing.JTextField();
        btnModelNumber = new javax.swing.JButton();
        jPanel7 = new javax.swing.JPanel();
        btnBrand = new javax.swing.JButton();
        jPanel10 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        txtCity = new javax.swing.JTextField();
        btnCity = new javax.swing.JButton();
        jPanel11 = new javax.swing.JPanel();
        btnExpiredMaintenanceCertificate = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jPanel8 = new javax.swing.JPanel();
        btnFleetTime = new javax.swing.JButton();
        txtFleetTime = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtManufacturer = new javax.swing.JTextField();
        btnSearchCarbyManufacturer = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        btnFirstAvailablePassengerCar = new javax.swing.JButton();
        btnAvailability1 = new javax.swing.JTextField();
        btnAvailability2 = new javax.swing.JTextField();
        btnCurrentAvailableCars = new javax.swing.JButton();
        btnCurrentUnavailableCars = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        btnYesCA = new javax.swing.JRadioButton();
        btnNoCA = new javax.swing.JRadioButton();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        txtBrand = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        txtMaxSeat = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        txtManufacturedYear1 = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        txtModelNo = new javax.swing.JTextField();
        txtAvailableCity = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        txtSerialNo = new javax.swing.JTextField();
        btnYesMC = new javax.swing.JRadioButton();
        jLabel18 = new javax.swing.JLabel();
        btnNoMC = new javax.swing.JRadioButton();
        btnConsolidatedSearch = new javax.swing.JButton();
        btnRefresh = new javax.swing.JButton();
        jLabel19 = new javax.swing.JLabel();
        minSeatComboBox = new javax.swing.JComboBox<>();
        maxSeatComboBox = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        searchTable = new javax.swing.JTable();
        btnViewFullDetails = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();

        btnBack.setText("<< Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        jLabel3.setText("SEARCH BY CRITERIA");

        jTabbedPane1.setTabLayoutPolicy(javax.swing.JTabbedPane.SCROLL_TAB_LAYOUT);

        jLabel4.setText("Enter the serial number of the car you wish to search:");

        btnSerialNumber.setText("Search");
        btnSerialNumber.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSerialNumberActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(60, 60, 60)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 340, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(27, 27, 27)
                        .addComponent(txtSerialNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(251, 251, 251)
                        .addComponent(btnSerialNumber)))
                .addContainerGap(68, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtSerialNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(29, 29, 29)
                .addComponent(btnSerialNumber)
                .addContainerGap(33, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Serial Number", jPanel5);

        jLabel2.setText("Cars manufactured in the year: ");

        SearchManufacturedYear.setText("Search");
        SearchManufacturedYear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SearchManufacturedYearActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(114, 114, 114)
                        .addComponent(jLabel2)
                        .addGap(42, 42, 42)
                        .addComponent(txtManufacturedYear, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(230, 230, 230)
                        .addComponent(SearchManufacturedYear)))
                .addContainerGap(177, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(58, 58, 58)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtManufacturedYear, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addComponent(SearchManufacturedYear)
                .addContainerGap(11, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Manufactured Year", jPanel4);

        jLabel5.setText("Min no of seats:");

        jLabel6.setText("Max no of seats:");

        seatComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4" }));

        seatComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6", "7" }));
        seatComboBox2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                seatComboBox2ActionPerformed(evt);
            }
        });

        btnSearchCapacity.setText("Search for Available Cars");
        btnSearchCapacity.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchCapacityActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addGap(61, 61, 61)
                .addComponent(jLabel5)
                .addGap(18, 18, 18)
                .addComponent(seatComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(82, 82, 82)
                .addComponent(jLabel6)
                .addGap(18, 18, 18)
                .addComponent(seatComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(98, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel9Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnSearchCapacity)
                .addGap(215, 215, 215))
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6)
                    .addComponent(seatComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(seatComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addComponent(btnSearchCapacity)
                .addContainerGap(34, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Seat Capacity", jPanel9);

        jLabel7.setText("Enter the model no of the car you wish to search:");

        btnModelNumber.setText("Search");
        btnModelNumber.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModelNumberActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(58, 58, 58)
                        .addComponent(jLabel7)
                        .addGap(29, 29, 29)
                        .addComponent(txtModelNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(266, 266, 266)
                        .addComponent(btnModelNumber)))
                .addContainerGap(105, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(txtModelNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btnModelNumber)
                .addContainerGap(39, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Model Number", jPanel6);

        btnBrand.setText("Car Manufacturers used by Uber");
        btnBrand.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBrandActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(165, 165, 165)
                .addComponent(btnBrand)
                .addContainerGap(200, Short.MAX_VALUE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(59, 59, 59)
                .addComponent(btnBrand)
                .addContainerGap(69, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Brand", jPanel7);

        jLabel9.setText("Search for car by City: ");

        btnCity.setText("Search Available Cars");
        btnCity.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCityActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel10Layout.createSequentialGroup()
                        .addGap(143, 143, 143)
                        .addComponent(jLabel9)
                        .addGap(18, 18, 18)
                        .addComponent(txtCity, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel10Layout.createSequentialGroup()
                        .addGap(200, 200, 200)
                        .addComponent(btnCity)))
                .addContainerGap(165, Short.MAX_VALUE))
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(txtCity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23)
                .addComponent(btnCity)
                .addContainerGap(26, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("City", jPanel10);

        btnExpiredMaintenanceCertificate.setText("Search");
        btnExpiredMaintenanceCertificate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExpiredMaintenanceCertificateActionPerformed(evt);
            }
        });

        jLabel8.setText("Maintenance Certificate of Cars:");

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Expired", "Active" }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel11Layout = new javax.swing.GroupLayout(jPanel11);
        jPanel11.setLayout(jPanel11Layout);
        jPanel11Layout.setHorizontalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel11Layout.createSequentialGroup()
                        .addGap(114, 114, 114)
                        .addComponent(jLabel8)
                        .addGap(38, 38, 38)
                        .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel11Layout.createSequentialGroup()
                        .addGap(272, 272, 272)
                        .addComponent(btnExpiredMaintenanceCertificate)))
                .addContainerGap(154, Short.MAX_VALUE))
        );
        jPanel11Layout.setVerticalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel11Layout.createSequentialGroup()
                .addGap(66, 66, 66)
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addComponent(btnExpiredMaintenanceCertificate)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Expired Maintenance Certificate", jPanel11);

        btnFleetTime.setText("Last Updated Fleet Time");
        btnFleetTime.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFleetTimeActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGap(96, 96, 96)
                .addComponent(btnFleetTime)
                .addGap(27, 27, 27)
                .addComponent(txtFleetTime, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(72, Short.MAX_VALUE))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnFleetTime)
                    .addComponent(txtFleetTime, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(75, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Fleet Update", jPanel8);

        jLabel1.setText("Search Car by Manufacturer : ");

        txtManufacturer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtManufacturerActionPerformed(evt);
            }
        });

        btnSearchCarbyManufacturer.setText("Search");
        btnSearchCarbyManufacturer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchCarbyManufacturerActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(88, 88, 88)
                        .addComponent(jLabel1)
                        .addGap(30, 30, 30)
                        .addComponent(txtManufacturer, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(240, 240, 240)
                        .addComponent(btnSearchCarbyManufacturer)))
                .addContainerGap(153, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(55, 55, 55)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtManufacturer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addComponent(btnSearchCarbyManufacturer)
                .addContainerGap(17, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Manufacturer", jPanel3);

        btnFirstAvailablePassengerCar.setText("First Available Passenger Car");
        btnFirstAvailablePassengerCar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFirstAvailablePassengerCarActionPerformed(evt);
            }
        });

        btnAvailability2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAvailability2ActionPerformed(evt);
            }
        });

        btnCurrentAvailableCars.setText("No of Cars currently available");
        btnCurrentAvailableCars.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCurrentAvailableCarsActionPerformed(evt);
            }
        });

        btnCurrentUnavailableCars.setText("No of Cars currently unavailable");
        btnCurrentUnavailableCars.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCurrentUnavailableCarsActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addGap(185, 185, 185)
                        .addComponent(btnFirstAvailablePassengerCar))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addGap(81, 81, 81)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnCurrentUnavailableCars, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnCurrentAvailableCars, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(27, 27, 27)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnAvailability2, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnAvailability1, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(149, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(btnFirstAvailablePassengerCar)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCurrentAvailableCars)
                    .addComponent(btnAvailability1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(16, 16, 16)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCurrentUnavailableCars)
                    .addComponent(btnAvailability2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(22, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Availability", jPanel1);

        btnGroupCA.add(btnYesCA);
        btnYesCA.setText("Yes");

        btnGroupCA.add(btnNoCA);
        btnNoCA.setText("No");

        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel10.setText("Car Availability:");

        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel11.setText("Brand:");

        txtBrand.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtBrandActionPerformed(evt);
            }
        });

        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel12.setText("Max no of Seats:");

        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel13.setText("Manufactured Year:");

        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel14.setText("Min no of Seats:");

        jLabel15.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel15.setText("Model Number:");

        jLabel16.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel16.setText("Available City:");

        jLabel17.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel17.setText("Serial Number:");

        btnGroupMC.add(btnYesMC);
        btnYesMC.setText("Yes");
        btnYesMC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnYesMCActionPerformed(evt);
            }
        });

        jLabel18.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel18.setText("Maintenance Certificate:");

        btnGroupMC.add(btnNoMC);
        btnNoMC.setText("No");

        btnConsolidatedSearch.setText("Search");
        btnConsolidatedSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConsolidatedSearchActionPerformed(evt);
            }
        });

        btnRefresh.setText("Refresh");
        btnRefresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRefreshActionPerformed(evt);
            }
        });

        jLabel19.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel19.setText("Max no of Seats:");

        minSeatComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4" }));

        maxSeatComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6", "7" }));
        maxSeatComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                maxSeatComboBoxActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel11)
                                .addComponent(jLabel10)
                                .addComponent(jLabel14)
                                .addComponent(jLabel19))
                            .addComponent(jLabel12)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel13)))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addComponent(txtMaxSeat))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(minSeatComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(maxSeatComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(txtBrand, javax.swing.GroupLayout.DEFAULT_SIZE, 109, Short.MAX_VALUE)
                                .addComponent(txtManufacturedYear1, javax.swing.GroupLayout.Alignment.LEADING)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                        .addComponent(btnYesCA)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnNoCA)))
                .addGap(26, 26, 26)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel16, javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel17, javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel15))
                            .addComponent(jLabel18, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(txtAvailableCity, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 109, Short.MAX_VALUE)
                                .addComponent(txtSerialNo, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(txtModelNo, javax.swing.GroupLayout.Alignment.LEADING))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(btnYesMC)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnNoMC)))
                        .addGap(53, 53, 53))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(btnRefresh)
                        .addGap(38, 38, 38)
                        .addComponent(btnConsolidatedSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(132, 132, 132))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel10)
                            .addComponent(btnYesCA)
                            .addComponent(btnNoCA)))
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtModelNo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtSerialNo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel11)
                        .addComponent(txtBrand, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel17, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtManufacturedYear1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(minSeatComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(maxSeatComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(42, 42, 42)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtMaxSeat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtAvailableCity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(2, 2, 2)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnYesMC)
                            .addComponent(btnNoMC))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnConsolidatedSearch)
                            .addComponent(btnRefresh))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );

        jTabbedPane1.addTab("Consolidated Search", jPanel2);

        searchTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Brand", "Model No", "Min Seats", "Max Seats", "City", "Year"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(searchTable);
        if (searchTable.getColumnModel().getColumnCount() > 0) {
            searchTable.getColumnModel().getColumn(0).setResizable(false);
            searchTable.getColumnModel().getColumn(1).setResizable(false);
            searchTable.getColumnModel().getColumn(2).setResizable(false);
            searchTable.getColumnModel().getColumn(3).setResizable(false);
            searchTable.getColumnModel().getColumn(4).setResizable(false);
            searchTable.getColumnModel().getColumn(5).setResizable(false);
        }

        btnViewFullDetails.setText("View Full Details of the selected Car >>");
        btnViewFullDetails.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewFullDetailsActionPerformed(evt);
            }
        });

        btnDelete.setText("Delete");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(btnBack)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(250, 250, 250)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 333, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 631, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(btnDelete)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(btnViewFullDetails, javax.swing.GroupLayout.PREFERRED_SIZE, 278, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 616, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addContainerGap(565, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnBack)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(35, 35, 35)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnDelete)
                    .addComponent(btnViewFullDetails))
                .addContainerGap(192, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        userProcessContainer.remove(this);
        CardLayout cardLayout = (CardLayout) userProcessContainer.getLayout();
        cardLayout.previous(userProcessContainer);
    }//GEN-LAST:event_btnBackActionPerformed

    private void txtManufacturerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtManufacturerActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtManufacturerActionPerformed

    private void seatComboBox2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_seatComboBox2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_seatComboBox2ActionPerformed

    private void SearchManufacturedYearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SearchManufacturedYearActionPerformed
        // TODO add your handling code here:
        DefaultTableModel dt = (DefaultTableModel) searchTable.getModel();
        dt.setRowCount(0);
        int year = Integer.parseInt(txtManufacturedYear.getText());
        for (Car car : carInformationList.getCarList()) {
            if (car.getManufactured_year() == year) {
            Object row[] = new Object[6];
            row[0] = car;
            row[1] = car.getModel_num();
            row[2] = car.getMin_seats();
            row[3] = car.getMax_seats();;
            row[4] = car.getAvailble_city();
            row[5] = car.getManufactured_year();
            dt.addRow(row);
            }
        }
        txtManufacturedYear.setText("");
    }//GEN-LAST:event_SearchManufacturedYearActionPerformed

    private void btnAvailability2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAvailability2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnAvailability2ActionPerformed

    private void btnFirstAvailablePassengerCarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFirstAvailablePassengerCarActionPerformed
        // TODO add your handling code here:

        DefaultTableModel dt = (DefaultTableModel) searchTable.getModel();
        dt.setRowCount(0);

        for (Car car : carInformationList.getCarList()) {
            if (car.isAvailable() == true) {
                Object row[] = new Object[6];
            row[0] = car;
            row[1] = car.getModel_num();
            row[2] = car.getMin_seats();
            row[3] = car.getMax_seats();;
            row[4] = car.getAvailble_city();
            row[5] = car.getManufactured_year();
                dt.addRow(row);
                break;
            }
        }

    }//GEN-LAST:event_btnFirstAvailablePassengerCarActionPerformed

    private void btnCurrentAvailableCarsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCurrentAvailableCarsActionPerformed
        // TODO add your handling code here:
        DefaultTableModel dt = (DefaultTableModel) searchTable.getModel();
        dt.setRowCount(0);
        int count = 0;
        for (Car car : carInformationList.getCarList()) {
            if (car.isAvailable() == true) {
                Object row[] = new Object[6];
            row[0] = car;
            row[1] = car.getModel_num();
            row[2] = car.getMin_seats();
            row[3] = car.getMax_seats();;
            row[4] = car.getAvailble_city();
            row[5] = car.getManufactured_year();
                dt.addRow(row);
                count++;
            }
        }
        
        btnAvailability1.setText(String.valueOf(count));
    }//GEN-LAST:event_btnCurrentAvailableCarsActionPerformed

    private void btnCurrentUnavailableCarsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCurrentUnavailableCarsActionPerformed
        // TODO add your handling code here:
        DefaultTableModel dt = (DefaultTableModel) searchTable.getModel();
        dt.setRowCount(0);
        int count = 0;
        for (Car car : carInformationList.getCarList()) {
            if (car.isAvailable() == false) {
                Object row[] = new Object[6];
            row[0] = car;
            row[1] = car.getModel_num();
            row[2] = car.getMin_seats();
            row[3] = car.getMax_seats();;
            row[4] = car.getAvailble_city();
            row[5] = car.getManufactured_year();
                dt.addRow(row);
                count++;
            }
        }
        btnAvailability2.setText(String.valueOf(count));
    }//GEN-LAST:event_btnCurrentUnavailableCarsActionPerformed

    private void btnSearchCarbyManufacturerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchCarbyManufacturerActionPerformed
        // TODO add your handling code here:

        DefaultTableModel dt = (DefaultTableModel) searchTable.getModel();
        dt.setRowCount(0);
        String brand = txtManufacturer.getText().toLowerCase();
        for (Car car : carInformationList.getCarList()) {
            if (car.getBrand().toLowerCase().equals(brand)) {
                Object row[] = new Object[6];
            row[0] = car;
            row[1] = car.getModel_num();
            row[2] = car.getMin_seats();
            row[3] = car.getMax_seats();;
            row[4] = car.getAvailble_city();
            row[5] = car.getManufactured_year();
                dt.addRow(row);
            }
        }
    }//GEN-LAST:event_btnSearchCarbyManufacturerActionPerformed

    private void btnSerialNumberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSerialNumberActionPerformed
        // TODO add your handling code here:
        DefaultTableModel dt = (DefaultTableModel) searchTable.getModel();
        dt.setRowCount(0);
        int serial = Integer.parseInt(txtSerialNumber.getText());
        for (Car car : carInformationList.getCarList()) {
            if (car.getSerial_num() == serial) {
                Object row[] = new Object[6];
            row[0] = car;
            row[1] = car.getModel_num();
            row[2] = car.getMin_seats();
            row[3] = car.getMax_seats();;
            row[4] = car.getAvailble_city();
            row[5] = car.getManufactured_year();
                dt.addRow(row);
            }
        }
        txtSerialNumber.setText("");
    }//GEN-LAST:event_btnSerialNumberActionPerformed

    private void btnModelNumberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModelNumberActionPerformed
        // TODO add your handling code here:
        DefaultTableModel dt = (DefaultTableModel) searchTable.getModel();
        dt.setRowCount(0);
        String model = txtModelNumber.getText().toLowerCase();
        for (Car car : carInformationList.getCarList()) {
            if (car.getModel_num().toLowerCase().equals(model)) {
                Object row[] = new Object[6];
            row[0] = car;
            row[1] = car.getModel_num();
            row[2] = car.getMin_seats();
            row[3] = car.getMax_seats();;
            row[4] = car.getAvailble_city();
            row[5] = car.getManufactured_year();
                dt.addRow(row);
            }
        }
        txtModelNumber.setText("");
    }//GEN-LAST:event_btnModelNumberActionPerformed

    private void btnCityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCityActionPerformed
        // TODO add your handling code here:
        DefaultTableModel dt = (DefaultTableModel) searchTable.getModel();
        dt.setRowCount(0);
        String city = txtCity.getText().toLowerCase();
        for (Car car : carInformationList.getCarList()) {
            if (car.getAvailble_city().toLowerCase().equals(city)) {
                Object row[] = new Object[6];
            row[0] = car;
            row[1] = car.getModel_num();
            row[2] = car.getMin_seats();
            row[3] = car.getMax_seats();;
            row[4] = car.getAvailble_city();
            row[5] = car.getManufactured_year();
                dt.addRow(row);
            }
        }
        txtCity.setText("");
    }//GEN-LAST:event_btnCityActionPerformed

    private void btnBrandActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBrandActionPerformed
        // TODO add your handling code here:
        DefaultTableModel dtm = (DefaultTableModel) searchTable.getModel();
        dtm.setRowCount(0);

        for (Car car : carInformationList.getCarList()) {

            Object row[] = new Object[6];
            row[0] = car;
            row[1] = car.getModel_num();
            row[2] = car.getMin_seats();
            row[3] = car.getMax_seats();;
            row[4] = car.getAvailble_city();
            row[5] = car.getManufactured_year();
            dtm.addRow(row);
        }

    }//GEN-LAST:event_btnBrandActionPerformed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:


    }//GEN-LAST:event_jComboBox1ActionPerformed
    public void populateTable1() {
        DefaultTableModel dtm = (DefaultTableModel) searchTable.getModel();
        dtm.setRowCount(0);

        for (Car car : carInformationList.getCarList()) {
            if (car.isMaintenance_certificate() == true) {

                Object row[] = new Object[6];
            row[0] = car;
            row[1] = car.getModel_num();
            row[2] = car.getMin_seats();
            row[3] = car.getMax_seats();;
            row[4] = car.getAvailble_city();
            row[5] = car.getManufactured_year();
                dtm.addRow(row);
            }
        }
    }

    public void populateTable2() {
        DefaultTableModel dtm = (DefaultTableModel) searchTable.getModel();
        dtm.setRowCount(0);

        for (Car car : carInformationList.getCarList()) {
            if (car.isMaintenance_certificate() == false) {
                Object row[] = new Object[6];
            row[0] = car;
            row[1] = car.getModel_num();
            row[2] = car.getMin_seats();
            row[3] = car.getMax_seats();;
            row[4] = car.getAvailble_city();
            row[5] = car.getManufactured_year();
                dtm.addRow(row);
            }
        }

    }
    
    private void populateTable(List<Car> carinformationlist) {
        DefaultTableModel dtm = (DefaultTableModel) searchTable.getModel();
        dtm.setRowCount(0);

        for (Car car : carinformationlist) {
            Object row[] = new Object[5];
            row[0] = car;
            row[1] = car.getModel_num();
            row[2] = car.getMin_seats();
            row[3] = car.getMax_seats();
            row[4] = car.getAvailble_city();
            dtm.addRow(row);
        }

    }
    
    private void btnExpiredMaintenanceCertificateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExpiredMaintenanceCertificateActionPerformed
        // TODO add your handling code here:
        int combo1 = jComboBox1.getSelectedIndex();

        if (combo1 == 0) {
            populateTable1();
        } else {
            populateTable2();
        }
    }//GEN-LAST:event_btnExpiredMaintenanceCertificateActionPerformed

    private void btnSearchCapacityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchCapacityActionPerformed
        // TODO add your handling code here
        int max = Integer.parseInt(String.valueOf(seatComboBox2.getSelectedItem()));
        int min = Integer.parseInt(String.valueOf(seatComboBox1.getSelectedItem()));
        DefaultTableModel dtm = (DefaultTableModel) searchTable.getModel();
        dtm.setRowCount(0);
        if (min > max) {
            JOptionPane.showMessageDialog(null, "Min no of seats cannot be greater than its max, Please select again!");
        }
        for (Car car : carInformationList.getCarList()) {

            if (min <= car.getMin_seats() && max >= car.getMax_seats()) {

                Object row[] = new Object[6];
            row[0] = car;
            row[1] = car.getModel_num();
            row[2] = car.getMin_seats();
            row[3] = car.getMax_seats();;
            row[4] = car.getAvailble_city();
            row[5] = car.getManufactured_year();
                dtm.addRow(row);
            }
        }

    }//GEN-LAST:event_btnSearchCapacityActionPerformed

    private void btnViewFullDetailsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewFullDetailsActionPerformed
        // TODO add your handling code here:
        int selectedRow = searchTable.getSelectedRow();
        if (selectedRow < 0) {
            JOptionPane.showConfirmDialog(null, "Please select a row from the table to view the details", "Warning", JOptionPane.WARNING_MESSAGE);
        } else {

            if (person.equals("admin")) {
                Car car = (Car) searchTable.getValueAt(selectedRow, 0);
                AdminViewFullDetailsJPanel adminpanel = new AdminViewFullDetailsJPanel(userProcessContainer, carInformationList, car);
                userProcessContainer.add("AdminViewFullDetailsJPanel", adminpanel);
                CardLayout layout = (CardLayout) userProcessContainer.getLayout();
                layout.next(userProcessContainer);
            } else {
                Car car = (Car) searchTable.getValueAt(selectedRow, 0);
                ViewFullDetailsJPanel panel = new ViewFullDetailsJPanel(userProcessContainer, carInformationList, car);
                userProcessContainer.add("ViewFullDetailsJPanel", panel);
                CardLayout layout = (CardLayout) userProcessContainer.getLayout();
                layout.next(userProcessContainer);
            }
        }
    }//GEN-LAST:event_btnViewFullDetailsActionPerformed

    private void txtBrandActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtBrandActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtBrandActionPerformed

    private void btnYesMCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnYesMCActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnYesMCActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        // TODO add your handling code here:
        int selectedrow = searchTable.getSelectedRow();
        if (selectedrow >= 0)
        {
            int dialogButton = JOptionPane.YES_NO_OPTION;
            int dialogResult = JOptionPane.showConfirmDialog(null, "Would you like to delete the account?", "Warning", dialogButton);
            if (dialogResult == JOptionPane.YES_OPTION)
            {
                Car car = (Car) searchTable.getValueAt(selectedrow, 0);
                carInformationList.deleteCar(car);
                JOptionPane.showMessageDialog(null, "Deleted successfully");
                populateTable();
            }

        }
        else 
            JOptionPane.showMessageDialog(null, "Please select a row");    
    }//GEN-LAST:event_btnDeleteActionPerformed

    private void btnFleetTimeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFleetTimeActionPerformed
        // TODO add your handling code here:
        txtFleetTime.setText(carInformationList.getLastUpdated() + "");
    }//GEN-LAST:event_btnFleetTimeActionPerformed

    private void btnRefreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRefreshActionPerformed
        // TODO add your handling code here:
        populateTable();
    }//GEN-LAST:event_btnRefreshActionPerformed

    private void btnConsolidatedSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConsolidatedSearchActionPerformed
        // TODO add your handling code here:
        templist.removeAll(templist);

        for (Car car : carInformationList.carInformationList) {
            //System.out.println((YesMainCert.isSelected()&&car.isMaintenance_certificate())||(NoMainCert.isSelected()&&!car.isMaintenance_certificate())||(NAmaincert.isSelected()));
            if ((txtBrand.getText().equals(car.getBrand()) || car.getBrand().equals(""))
                    && (txtModelNo.getText().equals(car.getModel_num())
                    || txtModelNo.getText().equals(""))
                    && (txtSerialNo.getText().equals(car.getSerial_num() + "")
                    || txtSerialNo.getText().equals(""))
                    && (txtAvailableCity.getText().equals(car.getAvailble_city())
                    || txtAvailableCity.getText().equals(""))
                    && ((!txtManufacturedYear1.getText().isEmpty()
                    && Integer.parseInt(txtManufacturedYear1.getText())
                    == car.getManufactured_year()) || txtManufacturedYear1.getText().isEmpty())
                    && (txtAvailableCity.getText().equals(car.getAvailble_city()) || txtAvailableCity.getText().equals("") )
                    && ( (btnYesCA.isSelected() == true &&
                        btnNoCA.isSelected() == false 
                    && btnYesCA.isSelected() == car.isAvailable())||(
                        btnNoCA.isSelected() == true &&
                        btnYesCA.isSelected() ==false && 
                    btnNoCA.isSelected() == !car.isAvailable())
                     || (btnYesCA.isSelected()==false && btnNoCA.isSelected() == false)) 
                    &&
                    ( (btnYesMC.isSelected() == true &&
                        btnNoMC.isSelected() == false 
                    && btnYesMC.isSelected() == car.isMaintenance_certificate())||(
                        btnNoMC.isSelected() == true &&
                        btnYesMC.isSelected() ==false && 
                    btnNoMC.isSelected() == !car.isMaintenance_certificate())
                     || (btnYesMC.isSelected()==false && btnNoMC.isSelected() == false))                 
                     &&
                    ((Integer.parseInt(String.valueOf(maxSeatComboBox.getSelectedItem())) >= car.getMax_seats()) ||
                    (Integer.parseInt(String.valueOf(minSeatComboBox.getSelectedItem())) <= car.getMin_seats())))
                    {
                templist.add(car);
            }

        }
        populateTable(templist);
        
    }//GEN-LAST:event_btnConsolidatedSearchActionPerformed

    private void maxSeatComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_maxSeatComboBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_maxSeatComboBoxActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton SearchManufacturedYear;
    private javax.swing.JTextField btnAvailability1;
    private javax.swing.JTextField btnAvailability2;
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnBrand;
    private javax.swing.JButton btnCity;
    private javax.swing.JButton btnConsolidatedSearch;
    private javax.swing.JButton btnCurrentAvailableCars;
    private javax.swing.JButton btnCurrentUnavailableCars;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnExpiredMaintenanceCertificate;
    private javax.swing.JButton btnFirstAvailablePassengerCar;
    private javax.swing.JButton btnFleetTime;
    private javax.swing.ButtonGroup btnGroupCA;
    private javax.swing.ButtonGroup btnGroupMC;
    private javax.swing.JButton btnModelNumber;
    private javax.swing.JRadioButton btnNoCA;
    private javax.swing.JRadioButton btnNoMC;
    private javax.swing.JButton btnRefresh;
    private javax.swing.JButton btnSearchCapacity;
    private javax.swing.JButton btnSearchCarbyManufacturer;
    private javax.swing.JButton btnSerialNumber;
    private javax.swing.JButton btnViewFullDetails;
    private javax.swing.JRadioButton btnYesCA;
    private javax.swing.JRadioButton btnYesMC;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JComboBox<String> maxSeatComboBox;
    private javax.swing.JComboBox<String> minSeatComboBox;
    private javax.swing.JTable searchTable;
    private javax.swing.JComboBox<String> seatComboBox1;
    private javax.swing.JComboBox<String> seatComboBox2;
    private javax.swing.JTextField txtAvailableCity;
    private javax.swing.JTextField txtBrand;
    private javax.swing.JTextField txtCity;
    private javax.swing.JTextField txtFleetTime;
    private javax.swing.JTextField txtManufacturedYear;
    private javax.swing.JTextField txtManufacturedYear1;
    private javax.swing.JTextField txtManufacturer;
    private javax.swing.JTextField txtMaxSeat;
    private javax.swing.JTextField txtModelNo;
    private javax.swing.JTextField txtModelNumber;
    private javax.swing.JTextField txtSerialNo;
    private javax.swing.JTextField txtSerialNumber;
    // End of variables declaration//GEN-END:variables
}
