/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface;

import Business.Car;
import Business.CarInformationList;
import java.awt.CardLayout;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author admin
 */
public class ViewFullDetailsJPanel extends javax.swing.JPanel {

    /**
     * Creates new form ViewFullDetailsJPanel
     */
    private Car car;
    private JPanel userProcessContainer;
    private CarInformationList carInformationList;

    ViewFullDetailsJPanel(JPanel userProcessContainer, CarInformationList carInformationList,Car carParam) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.carInformationList = carInformationList;
        this.car=carParam;
        populateAccountDetails();
    }

    private void populateAccountDetails(){
        txtAvailableCity.setText(car.getAvailble_city());
        txtBrand.setText(car.getBrand());
        if (car.isAvailable()==true){
        txtCarAvailability.setText("Yes");
        }
        else{
          txtCarAvailability.setText("No");  
        }
        if (car.isMaintenance_certificate()==true){
        txtMaintenanceCertificate.setText("Yes");
        }
        else{
          txtMaintenanceCertificate.setText("No");  
        }
        txtManufacturedYear.setText(String.valueOf(car.getManufactured_year()));
        txtMaxSeat.setText(String.valueOf(car.getMax_seats()));
        txtMinSeat.setText(String.valueOf(car.getMin_seats()));
        txtModelNo.setText(car.getModel_num());
        txtSerialNo.setText(String.valueOf(car.getSerial_num()));
        txtAvailableCity.setEnabled(false);
        txtBrand.setEnabled(false);
        txtCarAvailability.setEnabled(false);
        txtMaintenanceCertificate.setEnabled(false);
        txtManufacturedYear.setEnabled(false);
        txtMaxSeat.setEnabled(false);
        txtMinSeat.setEnabled(false);
        txtModelNo.setEnabled(false);
        txtSerialNo.setEnabled(false);
    }    
   


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */

    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel5 = new javax.swing.JLabel();
        txtMinSeat = new javax.swing.JTextField();
        txtMaxSeat = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtModelNo = new javax.swing.JTextField();
        txtAvailableCity = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        btnBack = new javax.swing.JButton();
        lblHeader = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtBrand = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtManufacturedYear = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtSerialNo = new javax.swing.JTextField();
        txtCarAvailability = new javax.swing.JTextField();
        txtMaintenanceCertificate = new javax.swing.JTextField();
        btnBook = new javax.swing.JButton();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel5.setText("Max no of Seats:");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 360, -1, 24));
        add(txtMinSeat, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 300, 210, -1));
        add(txtMaxSeat, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 360, 210, -1));

        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel6.setText("Model Number:");
        add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 120, -1, 24));

        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel7.setText("Available City:");
        add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 230, -1, 28));
        add(txtModelNo, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 120, 210, -1));
        add(txtAvailableCity, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 230, 210, -1));

        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel8.setText("Maintenance Certificate:");
        add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 290, -1, 28));

        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel9.setText("Serial Number:");
        add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 180, -1, 24));

        btnBack.setText("<Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });
        add(btnBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 69, -1, -1));

        lblHeader.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        lblHeader.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblHeader.setText("Car Details");
        add(lblHeader, new org.netbeans.lib.awtextra.AbsoluteConstraints(129, 66, 650, 32));

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel1.setText("Car Availability:");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(76, 129, -1, -1));

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel2.setText("Brand:");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(136, 189, -1, -1));

        txtBrand.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtBrandActionPerformed(evt);
            }
        });
        add(txtBrand, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 180, 210, -1));

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel3.setText("Manufactured Year:");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(54, 235, -1, -1));
        add(txtManufacturedYear, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 230, 210, -1));

        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel4.setText("Min no of Seats:");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(74, 294, -1, 24));
        add(txtSerialNo, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 180, 210, -1));
        add(txtCarAvailability, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 120, 61, -1));
        add(txtMaintenanceCertificate, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 290, 63, -1));

        btnBook.setText("Book a Ride");
        btnBook.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBookActionPerformed(evt);
            }
        });
        add(btnBook, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 430, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        userProcessContainer.remove(this);
        CardLayout cardLayout = (CardLayout)userProcessContainer.getLayout();
        cardLayout.previous(userProcessContainer);
    }//GEN-LAST:event_btnBackActionPerformed

    private void txtBrandActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtBrandActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtBrandActionPerformed

    private void btnBookActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBookActionPerformed
        // TODO add your handling code here:
        BookJPanel panel = new BookJPanel(userProcessContainer,carInformationList,car);
        userProcessContainer.add("BookJPanel",panel);
        CardLayout layout = (CardLayout)userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_btnBookActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnBook;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel lblHeader;
    private javax.swing.JTextField txtAvailableCity;
    private javax.swing.JTextField txtBrand;
    private javax.swing.JTextField txtCarAvailability;
    private javax.swing.JTextField txtMaintenanceCertificate;
    private javax.swing.JTextField txtManufacturedYear;
    private javax.swing.JTextField txtMaxSeat;
    private javax.swing.JTextField txtMinSeat;
    private javax.swing.JTextField txtModelNo;
    private javax.swing.JTextField txtSerialNo;
    // End of variables declaration//GEN-END:variables
}
